"""
Vision Executor

Handles vision-related actions using camera and llava model.
Automatically writes detailed results to Notepad.
"""

from typing import Dict, Any
import time
import pyautogui
from datetime import datetime
from utils.logger import log
from perception.camera_capture import get_camera, capture_camera_frame
from perception.vision_analyzer import get_vision_analyzer


class VisionExecutor:
    """Executor for vision-related operations."""
    
    def __init__(self):
        """Initialize vision executor."""
        self.camera = get_camera()
        self.analyzer = get_vision_analyzer()
        log.info("Vision executor initialized")
    
    def _write_to_notepad(self, content: str):
        """
        Open Notepad and write content with proper formatting.
        
        Args:
            content: Text content to write
        """
        try:
            log.info("📝 Opening Notepad to write vision results")
            
            # Open Notepad
            pyautogui.press('win')
            time.sleep(0.5)
            pyautogui.write('notepad', interval=0.05)
            time.sleep(0.3)
            pyautogui.press('enter')
            time.sleep(1.5)  # Wait for Notepad to open
            
            # Write content
            pyautogui.write(content, interval=0.01)
            
            log.info("✅ Content written to Notepad")
            
        except Exception as e:
            log.error(f"Failed to write to Notepad: {e}")
    
    def execute(self, action: str, params: Dict[str, Any]) -> Dict[str, Any]:
        """
        Execute a vision action.
        
        Args:
            action: Action name (vision_analyze, vision_answer, vision_detect_person)
            params: Action parameters
        
        Returns:
            Execution result
        """
        try:
            if action == "vision_analyze":
                return self._analyze_camera(params)
            elif action == "vision_answer":
                return self._answer_question(params)
            elif action == "vision_detect_person":
                return self._detect_person(params)
            else:
                raise ValueError(f"Unknown vision action: {action}")
        
        except Exception as e:
            log.error(f"Vision action '{action}' failed: {e}")
            return {
                "success": False,
                "error": str(e)
            }
    
    def _analyze_camera(self, params: Dict[str, Any]) -> Dict[str, Any]:
        """
        Analyze current camera feed.
        
        Params:
            - query (optional): Specific query about the image
        """
        log.info("📸 Analyzing camera feed")
        
        try:
            # Get current frame
            frame = self.camera.get_current_frame()
            
            if not frame:
                return {
                    "success": False,
                    "error": "Failed to capture camera frame. Camera may not be active."
                }
            
            # Analyze
            query = params.get("query", "Describe what you see in detail.")
            analysis = self.analyzer.analyze_frame(frame, query)
            
            # Format content for Notepad
            timestamp = datetime.now().strftime("%Y-%m-%d %H:%M:%S")
            notepad_content = f"""================================================
CAMERA VISION ANALYSIS
================================================
Date & Time: {timestamp}
Query: {query}

ANALYSIS RESULT:
------------------------------------------------
{analysis}

================================================
Generated by Agentic AI Vision System
================================================
"""
            
            # Write to Notepad
            self._write_to_notepad(notepad_content)
            
            return {
                "success": True,
                "analysis": analysis,
                "message": f"Vision analysis: {analysis[:100]}... (Written to Notepad)"
            }
        
        except Exception as e:
            log.error(f"Camera analysis failed: {e}")
            return {
                "success": False,
                "error": str(e)
            }
    
    def _answer_question(self, params: Dict[str, Any]) -> Dict[str, Any]:
        """
        Answer a specific question about camera feed.
        
        Params:
            - question (required): Question to answer
        """
        question = params.get("question", "")
        
        if not question:
            return {
                "success": False,
                "error": "No question provided"
            }
        
        log.info(f"📸 Answering visual question: {question}")
        
        try:
            # Get current frame
            frame = self.camera.get_current_frame()
            
            if not frame:
                return {
                    "success": False,
                    "error": "Failed to capture camera frame"
                }
            
            # Answer question
            answer = self.analyzer.answer_visual_question(frame, question)
            
            # Format content for Notepad
            timestamp = datetime.now().strftime("%Y-%m-%d %H:%M:%S")
            notepad_content = f"""================================================
CAMERA VISION Q&A
================================================
Date & Time: {timestamp}

QUESTION:
{question}

ANSWER:
------------------------------------------------
{answer}

================================================
Generated by Agentic AI Vision System
================================================
"""
            
            # Write to Notepad
            self._write_to_notepad(notepad_content)
            
            return {
                "success": True,
                "question": question,
                "answer": answer,
                "message": f"Answer: {answer[:100]}... (Written to Notepad)"
            }
        
        except Exception as e:
            log.error(f"Visual question answering failed: {e}")
            return {
                "success": False,
                "error": str(e)
            }
    
    def _detect_person(self, params: Dict[str, Any]) -> Dict[str, Any]:
        """
        Detect if person is present in camera.
        Special: Recognizes Divyanshu (boy in black t-shirt).
        """
        log.info("📸 Detecting person in camera")
        
        try:
            # Get current frame
            frame = self.camera.get_current_frame()
            
            if not frame:
                return {
                    "success": False,
                    "error": "Failed to capture camera frame"
                }
            
            # Detect person
            result = self.analyzer.detect_person(frame)
            
            # Format response
            if result["person_detected"]:
                if result["is_divyanshu"]:
                    message = "👤 DIVYANSHU DETECTED! (boy in black t-shirt)"
                    detection_status = "DIVYANSHU IDENTIFIED ✓"
                else:
                    message = "👤 Person detected in camera"
                    detection_status = "PERSON DETECTED"
            else:
                message = "No person detected in camera"
                detection_status = "NO PERSON DETECTED"
            
            # Format content for Notepad
            timestamp = datetime.now().strftime("%Y-%m-%d %H:%M:%S")
            notepad_content = f"""================================================
CAMERA PERSON DETECTION
================================================
Date & Time: {timestamp}

DETECTION STATUS: {detection_status}

DETAILED DESCRIPTION:
------------------------------------------------
{result['description']}

RECOGNITION DETAILS:
- Person Detected: {"YES" if result["person_detected"] else "NO"}
- Is Divyanshu: {"YES ✓" if result.get("is_divyanshu", False) else "NO"}

================================================
Generated by Agentic AI Vision System
================================================
"""
            
            # Write to Notepad
            self._write_to_notepad(notepad_content)
            
            return {
                "success": True,
                "person_detected": result["person_detected"],
                "is_divyanshu": result.get("is_divyanshu", False),
                "description": result["description"],
                "message": f"{message} (Written to Notepad)"
            }
        
        except Exception as e:
            log.error(f"Person detection failed: {e}")
            return {
                "success": False,
                "error": str(e)
            }


# Module-level instance
_executor = None


def get_vision_executor() -> VisionExecutor:
    """Get or create the vision executor singleton."""
    global _executor
    if _executor is None:
        _executor = VisionExecutor()
    return _executor
